packages:
  - apps/*
  - packages/*
  - tooling/*
  - providers/*

catalog:
  eslint: ^9.10.0
  typescript-eslint: ^8.3.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  zod: ^3.23.8
  "@t3-oss/env-core": ^0.11.1
  "@t3-oss/env-nextjs": ^0.11.1

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  node22:
    "@types/node": ^22.5.5
  node20:
    "@types/node": ^20.12.0
