apiVersion: v2
name: ctrlplane
description: Ctrlplane Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: webservice
    version: "*.*.*"
    repository: file://charts/webservice
    condition: webservice.install
