global:
  extraEnvFrom: {}
  extraEnv: {}

  common:
    labels: {}
    annotations: {}

webservice:
  install: true

job-policy-checker:
  install: true

ingress:
  create: true
  class: ""
  labels: {}
  annotations: {}
